### ISSUE TITLE
Output MongoDB update document instead of patch

### ISSUE THREAD

**Issue by yannick-cw** [eBay/bsonpatch#5]
Hi, I am looking into a similar issue right now, but my goal would be to have an mongo update in the end instead of a bson patch array. Have you considered something like that before? Use case would be sending only updates to mongoDB instead of replacing the whole document.

**Comment by dandoug** [comment]
Thanks for the suggestion.  Sorry it took me awhile to get around to reading it.  I don't spend much time maintaining this lib.

The whole point of this project is to keep this library as a straight port of [zjsonpatch](https://github.com/flipkart-incubator/zjsonpatch).  As such, adding the feature you are requesting if kind of out of scope.

I don't know much about what a `mongo update` would look like, but couldn't you essentially write some sort of static utility method to convert the `BsonArray` to the form that you want?
